### ISSUE TITLE
When releasing?

### ISSUE THREAD

**Issue by ThinkGeoduck** [AbhigyaKrishna/DBedWars#4]
when beta testing getting opened? ;)

**Comment by AbhigyaKrishna** [comment]
Soon TM

**Comment by ThinkGeoduck** [comment]
Find a Better Name :) and ETA please..

**Comment by AbhigyaKrishna** [comment]
`Dragon Bedwars` is the name and the eta would be around `15 days` for first playable release

**Comment by ThinkGeoduck** [comment]
Damn waiting..! Would be the first to try maybe :)
